apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-05
spec:
  replicas: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-05
  template:
    metadata:
      labels:
        app: guestbook-ui-05
    spec:
      containers:
      - image: quay.io/akuityio/alpine:latest
        name: guestbook-ui-05
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Mi"
            cpu: "20m"
        args:
          - '86400000'
        command:
          - sleep
