apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: alpine:latest
        name: guestbook-ui
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1Mi"
            cpu: "20m"
        args:
          - -c
          - "while true; do echo Argo CD && sleep 60; done"
        command:
          - sh
